language: node_js
node_js:
  - "4.6"
  - "4.4"
script:
  - "cp variables.ini.dist variables.ini"
  - "./configure --config-one theme:themeImagesPath.js"
  - "./configure --config-one theme:theme.json"
  - "./configure --config-one theme:variables.scss"
  - "npm run build"
  - "npm run travis-lint"
